FROM node:20

# Set working directory
WORKDIR /app

# Copy dependency declarations
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY frontend/ .

# Expose Vite dev port
EXPOSE 5173

# Default command
CMD ["npm", "run", "dev", "--", "--host"]